'use client'

import { useState } from 'react'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { Share2, Copy, Check, Download, Loader2 } from 'lucide-react'
import type { TravelAnalysisResponse } from '@/lib/analysis/schemas'

interface ShareExportDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  analysis: TravelAnalysisResponse
  query: string
}

export function ShareExportDialog({ open, onOpenChange, analysis, query }: ShareExportDialogProps) {
  const [sharing, setSharing] = useState(false)
  const [shareUrl, setShareUrl] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  const handleShare = async () => {
    setSharing(true)
    try {
      const response = await fetch('/api/share', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contentType: 'analysis',
          contentData: { analysis, query },
          isPublic: true,
          expiresInDays: 30,
        }),
      })

      if (response.ok) {
        const data = await response.json()
        const url = `${window.location.origin}/shared/${data.sharedContent.share_token}`
        setShareUrl(url)
      }
    } catch (error) {
      console.error('Failed to create share:', error)
    } finally {
      setSharing(false)
    }
  }

  const copyToClipboard = async () => {
    if (shareUrl) {
      await navigator.clipboard.writeText(shareUrl)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const handleExportPDF = () => {
    // Generate printable summary
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Travel Analysis - ${query}</title>
          <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
            h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
            h2 { color: #1e40af; margin-top: 30px; }
            .destination { background: #f3f4f6; padding: 15px; margin: 10px 0; border-radius: 8px; }
            .score { font-weight: bold; color: #059669; }
            .warning { background: #fef3c7; padding: 10px; border-left: 4px solid #f59e0b; margin: 10px 0; }
            @media print { body { margin: 0; } }
          </style>
        </head>
        <body>
          <h1>Travel Analysis Results</h1>
          <p><strong>Query:</strong> ${query}</p>
          <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
          
          <h2>Summary</h2>
          <p>${analysis.querySummary}</p>
          
          <h2>Top Recommendations</h2>
          <ul>
            ${analysis.topRecommendations.map(rec => `<li>${rec}</li>`).join('')}
          </ul>
          
          <h2>Ranked Destinations</h2>
          ${analysis.rankedDestinations.slice(0, 5).map((dest, i) => `
            <div class="destination">
              <h3>#${i + 1} ${dest.destinationName}</h3>
              <p class="score">Match Score: ${dest.totalMatchScore.toFixed(1)}/100</p>
              <p><strong>Type:</strong> ${dest.destinationType}</p>
              <p><strong>Why recommended:</strong></p>
              <ul>
                ${(dest.whyRecommended || []).slice(0, 3).map(reason => `<li>${reason}</li>`).join('')}
              </ul>
            </div>
          `).join('')}
          
          ${analysis.warnings.length > 0 ? `
            <h2>Important Warnings</h2>
            ${analysis.warnings.map(warning => `<div class="warning">${warning}</div>`).join('')}
          ` : ''}
          
          <p style="margin-top: 40px; color: #6b7280; font-size: 12px;">
            Generated by Travel Analysis AI • ${new Date().toLocaleDateString()}
          </p>
        </body>
        </html>
      `)
      printWindow.document.close()
      printWindow.print()
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Share2 className="h-5 w-5" />
            Share & Export
          </DialogTitle>
          <DialogDescription>
            Share your analysis results or export for offline use
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* Share Link */}
          <div className="space-y-3">
            <Label>Share Link</Label>
            {!shareUrl ? (
              <Button onClick={handleShare} disabled={sharing} className="w-full">
                {sharing ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Creating share link...
                  </>
                ) : (
                  <>
                    <Share2 className="h-4 w-4 mr-2" />
                    Generate Share Link
                  </>
                )}
              </Button>
            ) : (
              <div className="space-y-2">
                <div className="flex gap-2">
                  <Input value={shareUrl} readOnly className="flex-1" />
                  <Button variant="outline" size="icon" onClick={copyToClipboard}>
                    {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  </Button>
                </div>
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <Badge variant="outline" className="text-xs">Public</Badge>
                  <span>Expires in 30 days</span>
                </div>
              </div>
            )}
          </div>

          {/* Export Options */}
          <div className="space-y-3">
            <Label>Export</Label>
            <Button variant="outline" onClick={handleExportPDF} className="w-full">
              <Download className="h-4 w-4 mr-2" />
              Export as Printable Summary
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
